spring:
#  profiles:
#    include: oauth
  application:
   name: aircraft-positions
  security:
    oauth2:
      client:
        registration:
          okta:
            authorization-grant-type: authorization_code
            client-id: 0oahmm0xzkqEnHBtv5d7
            client-secret: rC2G2LhaFx-wvEaFWkV8jvQgxU49_U4kJMPgXHhBkaq9chExcw9UK2Kf0W2my4Z_
            scope: 
              - okta.users.read
              - okta.apiTokens.manage
              - okta.apiTokens.read
          kakao:
            client-id: de0392b4a2385db79af59bfb18eb4779
            client-secret: WZ6YPYbFeD65cXIzt1u0VsFZ633yIJ1g
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-name: kakao
            client-authentication-method: client_secret_post
            scope:
              - openid
              - profile_image
              - profile_nickname
        provider:
          okta:
            authorization-uri: https://dev-33910851.okta.com/oauth2/v1/authorize
            token-uri: https://dev-33910851.okta.com/oauth2/v1/token
            issuer-uri: https://dev-33910851.okta.com/oauth2/default
            jwk-set-uri: https://dev-33910851.okta.com/oauth2/v1/keys
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            issuer-uri: https://kauth.kakao.com
            user-name-attribute: sub
            
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
#  cloud:
#    stream:
#      bindings:
#        retrieveAircraftPositions-in-0:
#          destination: aircraftpositions
#          group: aircraftpositions
#          binder: rabbit
#  datasource:
#    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:mariadb://localhost:3306/chatting
#      username: ymshin
#      password: ymshin
#      connection-timeout: 30000
#      idle-timeout: 60000
#      max-lifetime: 1800000
#      maximum-pool-size: 20
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    view-names: pages/*

server:
  port: 8082

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.auth0.application: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
#okta:
#  oauth2:
#    client-id: 0oahmm0xzkqEnHBtv5d7
#    client-secret: rC2G2LhaFx-wvEaFWkV8jvQgxU49_U4kJMPgXHhBkaq9chExcw9UK2Kf0W2my4Z_
#    issuer: https://dev-33910851.okta.com/oauth2/default
